### ISSUE TITLE
Delay in nonce actualization causes bugs

### ISSUE THREAD

**Issue by tdelabro** [0xSpaceShard/starknet-devnet#793]
**Describe the bug (observed vs expected behavior)**

Sending a tx just after the previous one is accepected on l2, will result in reusing of the same nonce.
this is because the nonce is not immediately updated for `account.get_nonce`.

I have to do this to workaround
```
async fn wait_for_tx_completion<A: Account + ConnectedAccount + Sync>(
    account: Arc<A>,
    tx_hash: Felt,
) -> Result<(), ProviderError> {
    let nonce_before = account.get_nonce().await.unwrap();
    loop {
        match account.provider().get_transaction_status(tx_hash).await? {
            TransactionStatus::Received => {
                sleep(Duration::from_millis(500)).await;
                continue;
            }
            TransactionStatus::Rejected => {
                error!("tx-rejected");
                break;
            }
            TransactionStatus::AcceptedOnL2(TransactionExecutionStatus::Succeeded) => {
                info!("tx hash: {}", tx_hash);
                break;
            }
            TransactionStatus::AcceptedOnL2(TransactionExecutionStatus::Reverted) => {
                error!("tx-reverted");
                break;
            }
            TransactionStatus::AcceptedOnL1(_) => unreachable!(),
        }
    }

    loop {
        let nonce = account.get_nonce().await.unwrap();
        if nonce != nonce_before {
            break;
        } else {
            sleep(Duration::from_millis(500)).await;
        }
    }

    Ok(())
}
```  

**To Reproduce**

1. send a tx
2. wait for it status to be Succedded by polling `account.provider().get_transaction_status(transaction_hash: tx_hash).await?` in a loop
3. send a new transaction without specifying a custom nonce
4. it will return an error because the nonce is already used

**Devnet version**

- I am using Devnet version:
- [x] This happens with a dockerized Devnet (check the box if true).

image: "docker.io/shardlabs/starknet-devnet-rs:0.2.4-seed0"

**Comment by FabijanC** [comment]
I am not able to reproduce this. In my case, the `nonce_before` variable is already set to the value after tx execution, so I end up in an infinite loop. Even if I make the `nonce_before` a function parameter and if I obtain it before the transaction, I am not able to reproduce the issue (i.e. it immediately fetches the expected new nonce). The same behavior is in 0.2.4 (used by you) and 0.4.2 (the latest version at the time of writing).

**Comment by tdelabro** [comment]
>Even if I make the nonce_before a function parameter and if I obtain it before the transaction, I am not able to reproduce the issue

that is indeed the current state of my code, changed it after I posted this message.

I use docker compose with
```
  starknet-devnet:
    image: "docker.io/shardlabs/starknet-devnet-rs:0.2.4-seed0"
    environment:
      - SEED=0
      - BLOCK_GENERATION_ON=5
      - CHAIN_ID=SN_DEVNET
    ports:
      - "5050:5050"
    restart: always
    healthcheck:
      # Doing http calls without having to install curl or wget
      # https://github.com/dart-lang/dart-docker/issues/58#issuecomment-1410663799
      test: ["CMD", "bash", "-c", 'exec 3<>/dev/tcp/localhost/5050;echo -e "GET /is_alive HTTP/1.1\r\nHost: localhost:5050\r\nConnection: close\r\n\r\n" >&3; grep "200 OK" <&3']
      start_period: 1s
      interval: 3s
      retries: 3

```
